{% set name = "imbalanced-learn" %}
{% set version = "0.2.0" %}
{% set sha256 = "e9f814e5263a90a3b32d32935ccce10bda8d3fca8dbe334732e374b22dbd9a21" %}
package:
  name: imbalanced-learn
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - scipy
    - scikit-learn
    - nose

  run:
    - python
    - numpy x.x
    - scipy
    - scikit-learn

test:
  requires:
    - nose
    - coverage

  imports:
    - imblearn

  commands:
    - nosetests imblearn

about:
  home: https://github.com/scikit-learn-contrib/imbalanced-learn
  license: MIT
  license_file: LICENSE
  summary: 'Python module to perform under sampling and over sampling with various techniques'
  description: |
    imbalanced-learn is a python package offering a number of re-sampling techniques commonly
    used in datasets showing strong between-class imbalance. It is compatible with scikit-learn
    and is part of scikit-learn-contrib projects.
  doc_url: http://contrib.scikit-learn.org/imbalanced-learn
  dev_url: https://github.com/scikit-learn-contrib/imbalanced-learn

extra:
  recipe-maintainers:
    - glemaitre
